[project]
name = "my-demo-project"
version = "0.1.0"
description = ""
authors = [""]
readme = "README.md"
requires-python = "^3.12"
dependencies = [
    "requests (==2.31.0)
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
